# Generated by Django 4.2 on 2023-04-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_content_post_body_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='posts/images/thumbnails/null.jpg', upload_to='posts/images/thumbnails'),
        ),
    ]
