# Generated by Django 4.2 on 2023-04-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page_url',
            field=models.CharField(default='postnumbernull', max_length=100),
        ),
    ]
